/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trikitraki;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author julianamantilla
 */
public class Tablero3x3 extends javax.swing.JFrame {

    private juego j;
    private Color colorjugadorX;
    private Color colorjugadorO;
    private char turno;
    private Color actual;

    /**
     * Creates new form Tablero3x3
     */
    public Tablero3x3(juego jue) {
        initComponents();
        this.j = jue;
        if (this.j.getX().getColor().equals("Rojo")) {
            colorjugadorX = Color.red;
            colorjugadorO = Color.blue;
        } else {
            colorjugadorX = Color.blue;
            colorjugadorO = Color.red;
        }
        turno = 'X';
        actual = posicion00.getBackground();
    }

    private Tablero3x3() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Jugadas = new javax.swing.JTextField();
        posicion00 = new javax.swing.JButton();
        posicion01 = new javax.swing.JButton();
        posicion02 = new javax.swing.JButton();
        posicion12 = new javax.swing.JButton();
        posicion11 = new javax.swing.JButton();
        posicion10 = new javax.swing.JButton();
        posicion20 = new javax.swing.JButton();
        posicion21 = new javax.swing.JButton();
        posicion22 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        Jugadas.setEditable(false);
        Jugadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        posicion00.setBackground(new java.awt.Color(255, 204, 204));
        posicion00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion00ActionPerformed(evt);
            }
        });

        posicion01.setBackground(new java.awt.Color(255, 204, 204));
        posicion01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion01ActionPerformed(evt);
            }
        });

        posicion02.setBackground(new java.awt.Color(255, 204, 204));
        posicion02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion02ActionPerformed(evt);
            }
        });

        posicion12.setBackground(new java.awt.Color(255, 204, 204));
        posicion12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion12ActionPerformed(evt);
            }
        });

        posicion11.setBackground(new java.awt.Color(255, 204, 204));
        posicion11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion11ActionPerformed(evt);
            }
        });

        posicion10.setBackground(new java.awt.Color(255, 204, 204));
        posicion10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion10ActionPerformed(evt);
            }
        });

        posicion20.setBackground(new java.awt.Color(255, 204, 204));
        posicion20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion20ActionPerformed(evt);
            }
        });

        posicion21.setBackground(new java.awt.Color(255, 204, 204));
        posicion21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion21ActionPerformed(evt);
            }
        });

        posicion22.setBackground(new java.awt.Color(255, 204, 204));
        posicion22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(posicion20, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(posicion21, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(posicion22, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(posicion10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(posicion11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(posicion12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(posicion00, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(posicion01, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(posicion02, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Jugadas, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Jugadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(posicion02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(posicion00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(posicion01, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(posicion12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(posicion10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(posicion11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(posicion22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(posicion20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(posicion21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posicion00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion00ActionPerformed

        int decision=3;

        if (posicion00.getText().isEmpty()) {
            if (turno == 'X') {
                posicion00.setText("X");
                posicion00.setBackground(colorjugadorX);

                int resultado = j.getT().colocarFicha(0, 0, 'X');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: O");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha  X, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }
            } else {
                posicion00.setText("O");
                posicion00.setBackground(colorjugadorO);

                int resultado = j.getT().colocarFicha(0, 0, 'O');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: X");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha O, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }            
            }
        
        if(decision==0)
            reiniciar();            
        else if(decision==1 || decision==2)
            this.dispose();
        }        
    }//GEN-LAST:event_posicion00ActionPerformed

    private void posicion01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion01ActionPerformed
        int decision=3;

        if (posicion01.getText().isEmpty()) {
            if (turno == 'X') {
                posicion01.setText("X");
                posicion01.setBackground(colorjugadorX);

                int resultado = j.getT().colocarFicha(0, 1, 'X');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: O");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha  X, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }
            } else {
                posicion01.setText("O");
                posicion01.setBackground(colorjugadorO);

                int resultado = j.getT().colocarFicha(0, 1, 'O');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: X");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha O, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }            
            }
        
        if(decision==0)
            reiniciar();            
        else if(decision==1 || decision==2)
            this.dispose();
        }  
    }//GEN-LAST:event_posicion01ActionPerformed

    private void posicion02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion02ActionPerformed
       int decision=3;

        if (posicion02.getText().isEmpty()) {
            if (turno == 'X') {
                posicion02.setText("X");
                posicion02.setBackground(colorjugadorX);

                int resultado = j.getT().colocarFicha(0, 2, 'X');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: O");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha  X, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }
            } else {
                posicion02.setText("O");
                posicion02.setBackground(colorjugadorO);

                int resultado = j.getT().colocarFicha(0, 2, 'O');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: X");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha O, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }            
            }
        
        if(decision==0)
            reiniciar();            
        else if(decision==1 || decision==2)
            this.dispose();
        }  
    }//GEN-LAST:event_posicion02ActionPerformed

    private void posicion10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion10ActionPerformed
      int decision=3;

        if (posicion10.getText().isEmpty()) {
            if (turno == 'X') {
                posicion10.setText("X");
                posicion10.setBackground(colorjugadorX);

                int resultado = j.getT().colocarFicha(1, 0, 'X');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: O");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha  X, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }
            } else {
                posicion10.setText("O");
                posicion10.setBackground(colorjugadorO);

                int resultado = j.getT().colocarFicha(1, 0, 'O');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: X");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha O, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }            
            }
        
        if(decision==0)
            reiniciar();            
        else if(decision==1 || decision==2)
            this.dispose();
        }  
    }//GEN-LAST:event_posicion10ActionPerformed

    private void posicion11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion11ActionPerformed
       int decision=3;

        if (posicion11.getText().isEmpty()) {
            if (turno == 'X') {
                posicion11.setText("X");
                posicion11.setBackground(colorjugadorX);

                int resultado = j.getT().colocarFicha(1, 1, 'X');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: O");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha  X, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }
            } else {
                posicion11.setText("O");
                posicion11.setBackground(colorjugadorO);

                int resultado = j.getT().colocarFicha(1, 1, 'O');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: X");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha O, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }            
            }
        
        if(decision==0)
            reiniciar();            
        else if(decision==1 || decision==2)
            this.dispose();
        }  
    }//GEN-LAST:event_posicion11ActionPerformed

    private void posicion12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion12ActionPerformed
        int decision=3;

        if (posicion12.getText().isEmpty()) {
            if (turno == 'X') {
                posicion12.setText("X");
                posicion12.setBackground(colorjugadorX);

                int resultado = j.getT().colocarFicha(1, 2, 'X');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: O");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha  X, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }
            } else {
                posicion12.setText("O");
                posicion12.setBackground(colorjugadorO);

                int resultado = j.getT().colocarFicha(1, 2, 'O');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: X");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha O, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }            
            }
        
        if(decision==0)
            reiniciar();            
        else if(decision==1 || decision==2)
            this.dispose();
        }  
    }//GEN-LAST:event_posicion12ActionPerformed

    private void posicion20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion20ActionPerformed
       int decision=3;

        if (posicion20.getText().isEmpty()) {
            if (turno == 'X') {
                posicion20.setText("X");
                posicion20.setBackground(colorjugadorX);

                int resultado = j.getT().colocarFicha(2, 0, 'X');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: O");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha  X, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }
            } else {
                posicion20.setText("O");
                posicion20.setBackground(colorjugadorO);

                int resultado = j.getT().colocarFicha(2, 0, 'O');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: X");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha O, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }            
            }
        
        if(decision==0)
            reiniciar();            
        else if(decision==1 || decision==2)
            this.dispose();
        }  
    }//GEN-LAST:event_posicion20ActionPerformed

    private void posicion21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion21ActionPerformed
        int decision=3;

        if (posicion21.getText().isEmpty()) {
            if (turno == 'X') {
                posicion21.setText("X");
                posicion21.setBackground(colorjugadorX);

                int resultado = j.getT().colocarFicha(2, 1, 'X');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: O");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha  X, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }
            } else {
                posicion21.setText("O");
                posicion21.setBackground(colorjugadorO);

                int resultado = j.getT().colocarFicha(2, 1, 'O');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: X");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha O, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }            
            }
        
        if(decision==0)
            reiniciar();            
        else if(decision==1 || decision==2)
            this.dispose();
        }  
    }//GEN-LAST:event_posicion21ActionPerformed

    private void posicion22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion22ActionPerformed
       int decision=3;

        if (posicion22.getText().isEmpty()) {
            if (turno == 'X') {
                posicion22.setText("X");
                posicion22.setBackground(colorjugadorX);

                int resultado = j.getT().colocarFicha(2, 2, 'X');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: O");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha  X, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }
            } else {
                posicion22.setText("O");
                posicion22.setBackground(colorjugadorO);

                int resultado = j.getT().colocarFicha(2, 2, 'O');

                if (resultado == 0) {
                    Jugadas.setText("Ficha Proxima a Jugar: X");
                    turno = j.cambiarTurno(turno);
                } else if (resultado == 1) {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Ha ganado el jugador con la ficha O, ¿desea competir de nuevo?");
                } else {
                    Jugadas.setText("Partida Terminada");
                    j.finalizarPartida();

                    decision = JOptionPane.showInternalConfirmDialog(null, "Partida Empatada, ¿desea competir de nuevo?");
                }            
            }
        
        if(decision==0)
            reiniciar();            
        else if(decision==1 || decision==2)
            this.dispose();
        }  
    }//GEN-LAST:event_posicion22ActionPerformed

    private void reiniciar() {

        Jugadas.setText("");
        posicion00.setText("");
        posicion00.setBackground(actual);
        posicion01.setText("");
        posicion01.setBackground(actual);
        posicion02.setText("");
        posicion02.setBackground(actual);
        posicion10.setText("");
        posicion10.setBackground(actual);
        posicion11.setText("");
        posicion11.setBackground(actual);
        posicion12.setText("");
        posicion12.setBackground(actual);
        posicion20.setText("");
        posicion20.setBackground(actual);
        posicion21.setText("");
        posicion21.setBackground(actual);
        posicion22.setText("");
        posicion22.setBackground(actual);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero3x3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jugadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton posicion00;
    private javax.swing.JButton posicion01;
    private javax.swing.JButton posicion02;
    private javax.swing.JButton posicion10;
    private javax.swing.JButton posicion11;
    private javax.swing.JButton posicion12;
    private javax.swing.JButton posicion20;
    private javax.swing.JButton posicion21;
    private javax.swing.JButton posicion22;
    // End of variables declaration//GEN-END:variables
}
