package trikitraki;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author julianamantilla
 */
public class Principal extends javax.swing.JFrame {
    
    private juego j;
    
    /**
     * Creates new form trikiTraki
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        j = new juego();
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        coloresX = new javax.swing.ButtonGroup();
        tamañotablero = new javax.swing.ButtonGroup();
        coloresO = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        RojoX = new javax.swing.JRadioButton();
        RojoO = new javax.swing.JRadioButton();
        reiniciarJuego = new javax.swing.JButton();
        inicioJuego = new javax.swing.JButton();
        txtNombreJugadorX = new javax.swing.JTextField();
        txtNombreJugadorO = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tamaño3x3 = new javax.swing.JRadioButton();
        tamaño4x4 = new javax.swing.JRadioButton();
        tamaño5x5 = new javax.swing.JRadioButton();
        AzulX = new javax.swing.JRadioButton();
        AzulO = new javax.swing.JRadioButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        titulo.setFont(new java.awt.Font("Sathu", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("TRIKITRAQUE");

        jLabel10.setText("Nombre jugador X");

        jLabel11.setText("Nombre jugador O");

        coloresX.add(RojoX);
        RojoX.setSelected(true);
        RojoX.setText("Rojo");
        RojoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RojoXActionPerformed(evt);
            }
        });

        coloresO.add(RojoO);
        RojoO.setText("Rojo");
        RojoO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RojoOActionPerformed(evt);
            }
        });

        reiniciarJuego.setBackground(new java.awt.Color(255, 153, 153));
        reiniciarJuego.setText("Reiniciar Juego");
        reiniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarJuegoActionPerformed(evt);
            }
        });

        inicioJuego.setBackground(new java.awt.Color(255, 153, 153));
        inicioJuego.setText("Iniciar Juego");
        inicioJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioJuegoActionPerformed(evt);
            }
        });

        jLabel1.setText("Tamaño de Tablero");

        tamañotablero.add(tamaño3x3);
        tamaño3x3.setText("3x3");
        tamaño3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamaño3x3ActionPerformed(evt);
            }
        });

        tamañotablero.add(tamaño4x4);
        tamaño4x4.setText("4x4");
        tamaño4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamaño4x4ActionPerformed(evt);
            }
        });

        tamañotablero.add(tamaño5x5);
        tamaño5x5.setText("5x5");
        tamaño5x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamaño5x5ActionPerformed(evt);
            }
        });

        coloresX.add(AzulX);
        AzulX.setText("Azul");
        AzulX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AzulXActionPerformed(evt);
            }
        });

        coloresO.add(AzulO);
        AzulO.setSelected(true);
        AzulO.setText("Azul");
        AzulO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AzulOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreJugadorX, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreJugadorO, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RojoX, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(RojoO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AzulX)
                            .addComponent(AzulO)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(inicioJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(reiniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tamaño3x3)
                                .addGap(45, 45, 45)
                                .addComponent(tamaño4x4)
                                .addGap(51, 51, 51)
                                .addComponent(tamaño5x5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(42, 42, 42))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(titulo)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreJugadorX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RojoX)
                            .addComponent(AzulX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreJugadorO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RojoO)
                            .addComponent(AzulO)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tamaño3x3)
                            .addComponent(tamaño4x4)
                            .addComponent(tamaño5x5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inicioJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reiniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioJuegoActionPerformed

        String colorx = "";
        String coloro = "";
        if(RojoX.isSelected()){
            colorx="Rojo";
        }else{
            colorx="Azul";
        }
        if(RojoO.isSelected()){
            coloro="Rojo";
        }else{
            coloro="Azul";
        }
        j = new juego(this.txtNombreJugadorX.getText(), 'X', colorx , this.txtNombreJugadorO.getText(), 'O', coloro);
        
        if(tamaño3x3.isSelected()){
            Tablero3x3 t3x3 = new Tablero3x3(j);
            t3x3.setVisible(true);
            j.iniciarPartida(3);
        }else if(tamaño4x4.isSelected()){
            Tablero4x4 t4x4 = new Tablero4x4(j);
            t4x4.setVisible(true);
            j.iniciarPartida(4);
        }else if(tamaño5x5.isSelected()){
            Tablero5x5 t5x5 = new Tablero5x5(j);
            t5x5.setVisible(true);
            j.iniciarPartida(5);
        }
   
    }//GEN-LAST:event_inicioJuegoActionPerformed

    private void reiniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarJuegoActionPerformed

        this.txtNombreJugadorX.setText("");
        this.txtNombreJugadorO.setText("");
        coloresX.clearSelection();
        coloresO.clearSelection();
        tamañotablero.clearSelection();

    }//GEN-LAST:event_reiniciarJuegoActionPerformed

    private void tamaño3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamaño3x3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamaño3x3ActionPerformed

    private void tamaño4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamaño4x4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamaño4x4ActionPerformed

    private void tamaño5x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamaño5x5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamaño5x5ActionPerformed

    private void RojoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RojoXActionPerformed

        if(RojoX.isSelected())
            AzulO.setSelected(true);
        
    }//GEN-LAST:event_RojoXActionPerformed

    private void AzulXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AzulXActionPerformed

        if(AzulX.isSelected())
            RojoO.setSelected(true);
        

    }//GEN-LAST:event_AzulXActionPerformed

    private void RojoOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RojoOActionPerformed

        if(RojoO.isSelected())
            AzulX.setSelected(true);
    }//GEN-LAST:event_RojoOActionPerformed

    private void AzulOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AzulOActionPerformed

        if(AzulO.isSelected())
            RojoX.setSelected(true);

    }//GEN-LAST:event_AzulOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AzulO;
    private javax.swing.JRadioButton AzulX;
    private javax.swing.JRadioButton RojoO;
    private javax.swing.JRadioButton RojoX;
    private javax.swing.ButtonGroup coloresO;
    private javax.swing.ButtonGroup coloresX;
    private javax.swing.JButton inicioJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton reiniciarJuego;
    private javax.swing.JRadioButton tamaño3x3;
    private javax.swing.JRadioButton tamaño4x4;
    private javax.swing.JRadioButton tamaño5x5;
    private javax.swing.ButtonGroup tamañotablero;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtNombreJugadorO;
    private javax.swing.JTextField txtNombreJugadorX;
    // End of variables declaration//GEN-END:variables

    private String StringValueOf(char ficha) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
